services:
  linkding:
    image: sissbruecker/linkding:latest
    restart: unless-stopped
    environment:
      LD_SUPERUSER_NAME: ${LD_SUPERUSER_NAME}
      LD_SUPERUSER_PASSWORD: ${LD_SUPERUSER_PASSWORD}
      LD_CSRF_TRUSTED_ORIGINS: ${LD_CSRF_TRUSTED_ORIGINS}
    volumes:
      - linkding-data:/etc/linkding/data
volumes:
  linkding-data:
