services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-downloads:/downloads
volumes:
  qbittorrent-config:
  qbittorrent-downloads:
