services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    volumes:
      - calibre-web-config:/config
      - calibre-web-books:/books
volumes:
  calibre-web-config:
  calibre-web-books:
