import { base, firstProject, open, waitStatus } from "./lib.mjs";
const repo = process.argv[2] ?? "https://github.com/heroku/node-js-getting-started";
const env = process.argv[3] ?? "";
const { browser, page } = await open();
const project = await firstProject(page);
await page.goto(project + "/new?type=git", { waitUntil: "networkidle" });
await page.getByPlaceholder("https://github.com/vercel/next.js").fill(repo);
await page.getByPlaceholder("https://github.com/vercel/next.js").blur();
await page.waitForTimeout(2500);
if (env) await page.locator("textarea").fill(env);
await page.screenshot({ path: "/tmp/claude-1000/git-form.png" });
await page.getByRole("button", { name: "Create service" }).click();
// Creating never deploys; start the first deployment from the service page.
await page.waitForURL(/\/services\/[^/]+$/, { timeout: 30000 });
await page.getByRole("button", { name: "Deploy", exact: true }).first().click();
await page.waitForURL(/\/services\/[a-z0-9]+$/, { timeout: 30000 });
console.log("service:", page.url().replace(base, ""));
console.log("status:", await waitStatus(page, /Running|Failed|Crashed/, 600000));
await page.locator('a[href*="/deployments/"]').first().click();
await page.waitForTimeout(2500);
await page.screenshot({ path: "/tmp/claude-1000/git-deploy.png" });
await browser.close();
