services:
  kopia:
    image: kopia/kopia:latest
    restart: unless-stopped
    hostname: kopia
    command:
      - server
      - start
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_USER}
      - --server-password=${KOPIA_UI_PASSWORD}
    environment:
      KOPIA_PASSWORD: ${KOPIA_PASSWORD}
      USER: ${KOPIA_USER}
      TZ: Etc/UTC
    volumes:
      - kopia-config:/app/config
      - kopia-cache:/app/cache
      - kopia-logs:/app/logs
      - kopia-data:/data
      - kopia-repository:/repository
volumes:
  kopia-config:
  kopia-cache:
  kopia-logs:
  kopia-data:
  kopia-repository:
