services:
  emby:
    image: emby/embyserver:latest
    restart: unless-stopped
    environment:
      UID: "1000"
      GID: "1000"
    volumes:
      - emby-config:/config
      - emby-media:/media
volumes:
  emby-config:
  emby-media:
