services:
  glances:
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    pid: host
    environment:
      GLANCES_OPT: -w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
