import { proxyPaths } from "@/server/paths";
import { sizeToBytes, type CaddySettings, type ProxyDefaults } from "./config";
import type { HostModel, SiteModel } from "./model";
import { allTrusted, clientIpHeaderNames, type VisitorIp } from "@/lib/trusted-proxies";
import { safeRedirectUrl } from "@/lib/unknown-redirect";

/**
 * Caddyfile rendering. Caddy obtains and renews certificates by itself
 * (automatic HTTPS); Serve-managed certificates are used when present.
 */

export const CADDY_CONFIG_DIR = "/etc/caddy";
const GENERATED = "# Generated by Serve — changes are overwritten.";
const STATIC_FILES = "css|js|mjs|map|png|jpe?g|gif|webp|avif|svg|ico|woff2?|ttf|otf|eot|mp4|webm|mp3|wasm";
const STAGING = "https://acme-staging-v02.api.letsencrypt.org/directory";

/** The URL has no quotes, backslashes or braces; escape anyway so it can never leave the string. */
const quoted = (v: string) => v.replace(/[\\"]/g, "\\$&");

const tab = (lines: string[], depth = 1) =>
  lines
    .join("\n")
    .split("\n")
    .map((l) => (l ? "\t".repeat(depth) + l : l))
    .join("\n");

const ON: Required<ProxyDefaults> = { catchAll: true, unknownRedirect: null, unavailablePage: true, httpsRedirect: true };

export function caddyMainConfig(cfg: CaddySettings, opts: { email: string | null; staging: boolean; visitor: VisitorIp; defaults?: Required<ProxyDefaults> }) {
  const d = opts.defaults ?? ON;
  const global: string[] = ["admin localhost:2019", "grace_period 10s"];
  if (!d.httpsRedirect) global.push("auto_https disable_redirects");
  const email = cfg.email || opts.email;
  if (email) global.push(`email ${email}`);
  if (opts.staging) global.push(`acme_ca ${STAGING}`);
  global.push("log {", `\tlevel ${cfg.logLevel ?? "INFO"}`, "}");
  const servers: string[] = [`protocols h1 h2${cfg.http3 ? " h3" : ""}`];
  servers.push(...clientIpOptions(opts.visitor));
  const timeouts: string[] = [];
  if (cfg.readTimeout) timeouts.push(`read_body ${cfg.readTimeout}s`);
  if (cfg.writeTimeout) timeouts.push(`write ${cfg.writeTimeout}s`);
  if (cfg.idleTimeout) timeouts.push(`idle ${cfg.idleTimeout}s`);
  if (timeouts.length) servers.push("timeouts {", tab(timeouts), "}");
  global.push("servers {", tab(servers), "}");
  if (cfg.rawGlobal?.trim()) global.push("# Custom global options", cfg.rawGlobal.trim());

  const errors = d.unavailablePage
    ? `	handle_errors {
		root * ${proxyPaths.pages}
		@notfound expression {err.status_code} == 404
		handle @notfound {
			rewrite * /not-found.html
			file_server
		}
		handle {
			rewrite * /unavailable.html
			file_server
		}
	}`
    : `	# Serve's error pages are off: custom files handle errors.
	handle_errors 404 {
		root * ${proxyPaths.pages}
		rewrite * /not-found.html
		file_server
	}`;
  const redirect = safeRedirectUrl(d.unknownRedirect);
  const catchAll = d.catchAll
    ? `# Unknown hosts.
:80 {
	handle /__serve/health {
		respond "ok" 200
	}
	handle {
		${redirect ? `redir "${quoted(redirect)}" 302` : "error 404"}
	}
	import serve_errors
}
`
    : `# Serve's catch-all is off: only the health check answers here.
http://localhost:80, http://127.0.0.1:80 {
	respond /__serve/health "ok" 200
}
`;

  return `${GENERATED}
{
${tab(global)}
}

(serve_log) {
	log {
		output file ${proxyPaths.logs}/access.log {
			roll_disabled
		}
		format json
	}
}

(serve_errors) {
${errors}
}

${catchAll}
import ${proxyPaths.sites}/*.caddy
import ${proxyPaths.sites}/custom/*.caddy
`;
}

/** Header Caddy reads for every request that is safe to trust from the tunnel too. */
const tunnelSafe = (v: VisitorIp) => !v.header || v.header === "x-forwarded-for" || v.header === "cf-connecting-ip";

/** The tunnel network when Caddy's trusted_proxies leave it out (X-Real-IP, True-Client-IP): tunnel hosts then read CF-Connecting-IP themselves. */
export function tunnelTrustFor(v: VisitorIp) {
  return tunnelSafe(v) ? [] : v.tunnel;
}

/** Where Caddy takes the visitor IP from (client_ip in matchers, logs and client_ip_hash). */
function clientIpOptions(v: VisitorIp) {
  if (!v.header) {
    if (!v.tunnel.length) return [];
    // Tunnel traffic arrives from cloudflared on this network: trust its visitor IP headers, nobody else's.
    return [`trusted_proxies static ${v.tunnel.join(" ")}`, "client_ip_headers CF-Connecting-IP X-Forwarded-For"];
  }
  // Caddy reads one header for all traffic. A visitor can send X-Real-IP or True-Client-IP
  // through Cloudflare, so with those the tunnel is not trusted; X-Forwarded-For and
  // CF-Connecting-IP are written by Cloudflare's edge.
  const trusted = tunnelSafe(v) ? allTrusted(v) : v.ranges;
  if (!trusted.length) return [];
  const lines = [`trusted_proxies static ${trusted.join(" ")}`, `client_ip_headers ${clientIpHeaderNames[v.header]}`];
  // Right to left: the visitor is the last address no trusted proxy added.
  if (v.header === "x-forwarded-for") lines.push("trusted_proxies_strict");
  return lines;
}

/** Site address(es) for a host: HTTPS (with an explicit HTTP redirect block), HTTPS without redirect, or plain HTTP. */
function addresses(h: HostModel) {
  if (!h.https) return `http://${h.hostname}`;
  if (!h.forceHttps) return `https://${h.hostname}, http://${h.hostname}`;
  return `https://${h.hostname}`;
}

function headerLines(o: SiteModel["options"], tls: boolean) {
  const lines: string[] = [];
  // nginx adds HSTS on every TLS site; do the same.
  if (tls) lines.push(`>Strict-Transport-Security "max-age=31536000${o?.securityHeaders ? "; includeSubDomains" : ""}"`);
  if (o?.securityHeaders) {
    lines.push(`>X-Content-Type-Options "nosniff"`, `>Referrer-Policy "strict-origin-when-cross-origin"`, `>X-Frame-Options "SAMEORIGIN"`);
  }
  for (const h of o?.headers ?? []) lines.push(`>${h.name} "${h.value}"`);
  return lines;
}

function routeBody(site: SiteModel, h: HostModel, targets: string[] | null, realIp: boolean, tunnelRanges: string[]) {
  const o = site.options;
  const lines: string[] = [];
  // A tunnel host while Caddy reads a header the tunnel is not trusted for: the visitor is
  // cloudflared's CF-Connecting-IP when the request came from the tunnel network (like nginx).
  const viaTunnel = realIp && h.tunnel && tunnelRanges.length > 0;
  if (viaTunnel)
    lines.push(
      `@serve_via_tunnel remote_ip ${tunnelRanges.join(" ")}`,
      `@serve_not_tunnel not remote_ip ${tunnelRanges.join(" ")}`,
      "request_header @serve_via_tunnel X-Real-IP {http.request.header.CF-Connecting-IP}",
      "request_header @serve_not_tunnel X-Real-IP {client_ip}",
    );
  const allow = [...(h.allow ?? []), ...(o?.allow ?? [])];
  if (o?.deny?.length) lines.push(`@serve_denied client_ip ${o.deny.join(" ")}`, "respond @serve_denied 403");
  if (allow.length) lines.push(`@serve_blocked not client_ip ${allow.join(" ")}`, "respond @serve_blocked 403");
  const m = site.maintenance;
  if (m) {
    // Visitors on the allow list still reach the app; everyone else gets the page with a 503.
    lines.push(
      m.allow.length ? `@serve_maintenance not client_ip ${m.allow.join(" ")}` : "@serve_maintenance path *",
      "handle @serve_maintenance {",
      tab([`header Retry-After "${m.retryAfter}"`, `header Cache-Control "no-store"`, `root * ${proxyPaths.pages}`, `rewrite * /${m.page}`, "file_server {", "\tstatus 503", "}"]),
      "}",
    );
  }
  if (o?.maxBodySize) lines.push("request_body {", `\tmax_size ${sizeToBytes(o.maxBodySize) ?? o.maxBodySize}`, "}");
  if (o?.gzip !== false) lines.push("encode zstd gzip");
  const headers = headerLines(o, h.https);
  if (headers.length) lines.push("header {", tab(headers), "}");
  if (o?.corsOrigins?.length) {
    const cors = [
      `>Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS"`,
      `>Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin, X-Requested-With"`,
      `>Access-Control-Max-Age "86400"`,
      `>Vary "Origin"`,
    ];
    if (o.corsOrigins.includes("*")) lines.push("header {", tab([`>Access-Control-Allow-Origin "*"`, ...cors]), "}");
    else {
      const re = o.corsOrigins.map((v) => v.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|");
      lines.push(`@serve_cors header_regexp Origin ^(${re})$`, "header @serve_cors {", tab([`>Access-Control-Allow-Origin "{http.request.header.Origin}"`, ...cors]), "}");
    }
    // Preflights carry no credentials: answer them before basic auth.
    lines.push("@serve_preflight method OPTIONS", "respond @serve_preflight 204");
  }
  if (o?.basicAuth) {
    if (o.basicAuth.bcryptHash) lines.push("basic_auth {", `\t${o.basicAuth.username} ${o.basicAuth.bcryptHash}`, "}");
    // An apr1-only hash (saved before Caddy support) cannot be verified: fail closed.
    else lines.push(`respond "Password protection must be saved again in Serve for Caddy." 503`);
  }
  if (o?.cacheStatic) lines.push(`@serve_static path_regexp \\.(${STATIC_FILES})$`, `header @serve_static >Cache-Control "public, max-age=604800"`);
  if (o?.caddyDirectives?.trim()) lines.push("# Custom directives", o.caddyDirectives.trim());
  if (!targets) lines.push(site.stopped ? "error 503" : "error 502");
  else {
    // client_ip_hash uses the real visitor IP (trusted_proxies covers the tunnel).
    const proxy: string[] = [`lb_policy ${o?.sticky && targets.length > 1 ? "client_ip_hash" : "round_robin"}`, "lb_try_duration 5s"];
    const transport: string[] = [];
    if (o?.connectTimeout) transport.push(`dial_timeout ${o.connectTimeout}s`);
    if (o?.readTimeout) transport.push(`read_timeout ${o.readTimeout}s`, `write_timeout ${o.readTimeout}s`);
    if (transport.length) proxy.push("transport http {", tab(transport), "}");
    if (o?.buffering === false) proxy.push("flush_interval -1");
    if (o?.websockets === false) proxy.push("header_up -Upgrade", "header_up -Connection");
    // Caddy appends the nearest proxy to X-Forwarded-For; give apps the visitor it resolved too (as nginx does).
    if (realIp && !viaTunnel) proxy.push("header_up X-Real-IP {client_ip}");
    lines.push(`reverse_proxy ${targets.join(" ")} {`, tab(proxy), "}");
  }
  return lines;
}

/**
 * `realIp`: apps get the resolved visitor in X-Real-IP (trusted proxies on, and always for the
 * dashboard). `tunnelRanges`: the tunnel network, when Caddy's header does not trust it (tunnelTrustFor).
 */
export function renderCaddySite(site: SiteModel, defaults: Required<ProxyDefaults> = ON, realIp = false, tunnelRanges: string[] = []) {
  const blocks = [`${GENERATED} ${site.title}.`];
  for (const h of site.hosts) {
    const inner: string[] = ["import serve_log", "import serve_errors"];
    if (h.tls) inner.push(`tls ${h.tls.cert} ${h.tls.key}`);
    if (h.redirectTo) inner.push(`redir ${h.redirectTo.replace(/\/$/, "")}{uri} 308`);
    else {
      const targets = h.upstream ? (site.upstreams.find((u) => u.key === h.upstream)?.targets ?? []) : [];
      inner.push("route {", tab(routeBody(site, h, targets.length ? targets : null, realIp, tunnelRanges)), "}");
    }
    blocks.push(`${addresses(h)} {\n${tab(inner)}\n}`);
    // The :80 catch-all would win over Caddy's automatic redirect, so redirect explicitly.
    if (h.https && h.forceHttps && defaults.httpsRedirect) blocks.push(`http://${h.hostname} {\n${tab(["import serve_log", `redir https://{host}{uri} 308`])}\n}`);
  }
  return `${blocks.join("\n\n")}\n`;
}
