import YAML from "yaml";
import { proxyPaths } from "@/server/paths";
import { sizeToBytes, type ProxyDefaults, type TraefikSettings } from "./config";
import type { HostModel, SiteModel } from "./model";

/**
 * Traefik rendering: static configuration as command-line arguments and one
 * dynamic YAML file per site in the watched sites directory. Traefik obtains
 * certificates through its "le" ACME resolver.
 */

export const GENERATED = "# Generated by Serve — changes are overwritten.";
const STATIC_FILES = "css|js|mjs|map|png|jpe?g|gif|webp|avif|svg|ico|woff2?|ttf|otf|eot|mp4|webm|mp3|wasm";
const STAGING = "https://acme-staging-v02.api.letsencrypt.org/directory";
export const TRAEFIK_API = "http://127.0.0.1:8080";

type Obj = Record<string, unknown>;

export function traefikStaticArgs(cfg: TraefikSettings, opts: { email: string | null; staging: boolean; trusted: string[]; hasDnsToken: boolean }) {
  const args = [
    "--global.checknewversion=false",
    "--global.sendanonymoususage=false",
    "--entrypoints.web.address=:80",
    "--entrypoints.websecure.address=:443",
    // API, ping and metrics only on loopback inside the container: other containers on the network cannot read routes.
    "--entrypoints.traefik.address=127.0.0.1:8080",
    "--api=true",
    "--api.insecure=true",
    "--ping=true",
    `--providers.file.directory=${proxyPaths.sites}`,
    "--providers.file.watch=true",
    `--log.level=${cfg.logLevel ?? "INFO"}`,
    "--log.nocolor=true",
  ];
  if (opts.trusted.length) {
    // Tunnel traffic arrives from cloudflared on this network: trust its forwarded headers, nobody else's.
    for (const ep of ["web", "websecure"]) args.push(`--entrypoints.${ep}.forwardedHeaders.trustedIPs=${opts.trusted.join(",")}`);
  }
  if (cfg.accessLog !== false) {
    args.push(
      "--accesslog=true",
      `--accesslog.filepath=${proxyPaths.logs}/access.log`,
      "--accesslog.format=json",
      "--accesslog.fields.headers.defaultmode=drop",
      "--accesslog.fields.headers.names.User-Agent=keep",
      "--accesslog.fields.headers.names.Referer=keep",
    );
  }
  if (cfg.metrics) args.push("--metrics.prometheus=true", "--metrics.prometheus.entrypoint=traefik");
  if (cfg.dashboard?.enabled) args.push("--api.dashboard=true");
  if (opts.email) {
    args.push(`--certificatesresolvers.le.acme.email=${opts.email}`, "--certificatesresolvers.le.acme.storage=/data/acme.json");
    if (opts.staging) args.push(`--certificatesresolvers.le.acme.caserver=${STAGING}`);
    const challenge = cfg.acmeChallenge ?? "http";
    if (challenge === "dns-cloudflare" && opts.hasDnsToken) args.push("--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare");
    else if (challenge === "tls") args.push("--certificatesresolvers.le.acme.tlschallenge=true");
    else args.push("--certificatesresolvers.le.acme.httpchallenge.entrypoint=web");
  }
  return args;
}

/** Shared routers, middlewares and the error-page service. */
export function traefikBaseDynamic(opts: { pagesUrl: string; resolver: boolean; dashboard: TraefikSettings["dashboard"]; defaults: Required<ProxyDefaults> }) {
  const routers: Obj = opts.defaults.catchAll
    ? {
        "serve-catchall-web": { rule: "PathPrefix(`/`)", priority: 1, entryPoints: ["web"], service: "serve-pages" },
        "serve-catchall-secure": { rule: "PathPrefix(`/`)", priority: 1, entryPoints: ["websecure"], service: "serve-pages", tls: {} },
      }
    : {};
  const middlewares: Obj = { "serve-redirect-https": { redirectScheme: { scheme: "https", permanent: true } } };
  if (opts.defaults.unavailablePage) {
    middlewares["serve-errors"] = { errors: { status: ["500-599"], service: "serve-pages", query: "/__unavailable" } };
    middlewares["serve-unavailable"] = { replacePath: { path: "/__unavailable" } };
  }
  if (opts.dashboard?.enabled && opts.dashboard.hostname) {
    middlewares["serve-traefik-dashboard-auth"] = { basicAuth: { users: [`${opts.dashboard.username}:${opts.dashboard.passwordHash}`], removeHeader: true } };
    routers["serve-traefik-dashboard"] = {
      rule: `Host(\`${opts.dashboard.hostname}\`)`,
      entryPoints: ["websecure"],
      service: "api@internal",
      middlewares: ["serve-traefik-dashboard-auth"],
      tls: opts.resolver ? { certResolver: "le" } : {},
    };
  }
  return `${GENERATED}\n${YAML.stringify({
    // Traefik rejects empty maps ("routers cannot be a standalone element").
    http: { ...(Object.keys(routers).length ? { routers } : {}), middlewares, services: { "serve-pages": { loadBalancer: { servers: [{ url: opts.pagesUrl }] } } } },
  })}`;
}

function hostRule(h: HostModel, deny: string[] | undefined) {
  const base = `Host(\`${h.hostname}\`)`;
  if (!deny?.length) return base;
  // Traefik has no deny list: denied clients do not match the site and get the 404 page.
  return `${base} && !(${deny.map((d) => `ClientIP(\`${d}\`)`).join(" || ")})`;
}

export function renderTraefikSite(site: SiteModel, opts: { resolver: boolean; trusted: string[]; defaults?: Required<ProxyDefaults> }) {
  const defaults = opts.defaults ?? { catchAll: true, unavailablePage: true, httpsRedirect: true };
  const o = site.options;
  const p = site.name;
  const routers: Obj = {};
  const middlewares: Obj = {};
  const services: Obj = {};
  const transports: Obj = {};
  const certificates: { certFile: string; keyFile: string }[] = [];

  // Site-wide middleware chain.
  const chain: string[] = defaults.unavailablePage ? ["serve-errors"] : [];
  const allowAll = [...new Set([...(site.hosts[0]?.allow ?? []), ...(o?.allow ?? [])])];
  if (allowAll.length) {
    middlewares[`${p}-allow`] = { ipAllowList: { sourceRange: allowAll, ...(opts.trusted.length ? { ipStrategy: { excludedIPs: opts.trusted } } : {}) } };
    chain.push(`${p}-allow`);
  }
  const headers: Obj = {};
  const custom: Record<string, string> = {};
  for (const h of o?.headers ?? []) custom[h.name] = h.value;
  if (Object.keys(custom).length) headers.customResponseHeaders = custom;
  if (o?.securityHeaders)
    Object.assign(headers, { contentTypeNosniff: true, referrerPolicy: "strict-origin-when-cross-origin", customFrameOptionsValue: "SAMEORIGIN", stsIncludeSubdomains: true });
  if (o?.corsOrigins?.length) {
    Object.assign(headers, {
      accessControlAllowOriginList: o.corsOrigins,
      accessControlAllowMethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
      accessControlAllowHeaders: ["Authorization", "Content-Type", "Accept", "Origin", "X-Requested-With"],
      accessControlMaxAge: 86400,
      addVaryHeader: true,
    });
  }
  if (o?.websockets === false) headers.customRequestHeaders = { Upgrade: "", Connection: "" };
  if (Object.keys(headers).length) {
    middlewares[`${p}-headers`] = { headers };
    chain.push(`${p}-headers`);
  }
  if (o?.basicAuth) {
    middlewares[`${p}-auth`] = { basicAuth: { users: [`${o.basicAuth.username}:${o.basicAuth.passwordHash}`], removeHeader: true } };
    chain.push(`${p}-auth`);
  }
  if (o?.maxBodySize) {
    middlewares[`${p}-body`] = { buffering: { maxRequestBodyBytes: sizeToBytes(o.maxBodySize) ?? 104857600 } };
    chain.push(`${p}-body`);
  }
  if (o?.gzip !== false) {
    middlewares[`${p}-compress`] = { compress: {} };
    chain.push(`${p}-compress`);
  }
  if (o?.traefikMiddlewares?.trim()) {
    const extra = YAML.parse(o.traefikMiddlewares) as Record<string, Obj>;
    for (const [name, def] of Object.entries(extra ?? {})) {
      middlewares[`${p}-x-${name}`] = def;
      chain.push(`${p}-x-${name}`);
    }
  }
  if (o?.cacheStatic) middlewares[`${p}-static`] = { headers: { customResponseHeaders: { "Cache-Control": "public, max-age=604800" } } };

  let transport: string | undefined;
  if (o?.connectTimeout || o?.readTimeout) {
    transport = `${p}-transport`;
    transports[transport] = {
      forwardingTimeouts: {
        ...(o.connectTimeout ? { dialTimeout: `${o.connectTimeout}s` } : {}),
        ...(o.readTimeout ? { responseHeaderTimeout: `${o.readTimeout}s`, idleConnTimeout: `${o.readTimeout}s` } : {}),
      },
    };
  }
  for (const u of site.upstreams) {
    if (!u.targets.length) continue;
    services[`${p}-${u.key}`] = {
      loadBalancer: {
        passHostHeader: true,
        servers: u.targets.map((t) => ({ url: `http://${t}` })),
        ...(o?.buffering === false ? { responseForwarding: { flushInterval: "1ms" } } : {}),
        ...(transport ? { serversTransport: transport } : {}),
      },
    };
  }

  const m = site.maintenance;
  if (m) {
    middlewares[`${p}-maintenance`] = { replacePath: { path: `/__maintenance/${site.serviceId}` } };
    middlewares[`${p}-maintenance-headers`] = { headers: { customResponseHeaders: { "Retry-After": String(m.retryAfter), "Cache-Control": "no-store" } } };
  }

  site.hosts.forEach((h, i) => {
    const base = `${p}-${i}`;
    const rule = hostRule(h, o?.deny);
    const tls = h.https ? (h.tls ? {} : opts.resolver ? { certResolver: "le" } : {}) : undefined;
    if (h.tls) certificates.push({ certFile: h.tls.cert, keyFile: h.tls.key });

    let service: string;
    let mws: string[];
    if (h.redirectTo) {
      middlewares[`${base}-redirect`] = { redirectRegex: { regex: "^https?://[^/]+(.*)$", replacement: `${h.redirectTo.replace(/\/$/, "")}\${1}`, permanent: true } };
      service = "noop@internal";
      mws = [`${base}-redirect`];
    } else {
      const targets = h.upstream ? site.upstreams.find((u) => u.key === h.upstream)?.targets : undefined;
      if (targets?.length) {
        service = `${p}-${h.upstream}`;
        mws = chain;
      } else if (defaults.unavailablePage) {
        // Stopped or not running: Serve's 503 page.
        service = "serve-pages";
        mws = ["serve-unavailable"];
      } else if (m) {
        service = "serve-pages";
        mws = [];
      } else {
        // The 503 page is off: custom files decide what these hosts answer.
        return;
      }
    }
    // Maintenance: the page for everyone, and (longer rule, higher priority) the app for the allow list.
    let allowed: { service: string; mws: string[] } | null = null;
    if (m && !h.redirectTo) {
      if (m.allow.length && service !== "serve-pages") allowed = { service, mws };
      service = "serve-pages";
      mws = [`${p}-maintenance-headers`, `${p}-maintenance`];
    }
    const add = (name: string, entryPoints: string[], extra: Obj, middlewareList: string[], r = rule, svc = service) => {
      routers[name] = { rule: r, entryPoints, service: svc, ...(middlewareList.length ? { middlewares: middlewareList } : {}), ...extra };
    };
    if (allowed) {
      const allowRule = `${rule} && (${m!.allow.map((a) => `ClientIP(\`${a}\`)`).join(" || ")})`;
      if (!(h.https && h.forceHttps)) add(`${base}-web-allowed`, ["web"], {}, allowed.mws, allowRule, allowed.service);
      if (h.https) add(`${base}-secure-allowed`, ["websecure"], { tls }, allowed.mws, allowRule, allowed.service);
    }
    if (h.https && h.forceHttps) {
      // With Serve's redirects off, custom files handle HTTP for HTTPS-only hosts.
      if (defaults.httpsRedirect) routers[`${base}-web`] = { rule, entryPoints: ["web"], service: "noop@internal", middlewares: ["serve-redirect-https"] };
    } else add(`${base}-web`, ["web"], {}, mws);
    if (h.https) add(`${base}-secure`, ["websecure"], { tls }, mws);
    if (o?.cacheStatic && !h.redirectTo && mws === chain) {
      const staticRule = `${rule} && PathRegexp(\`\\.(${STATIC_FILES})$\`)`;
      if (!(h.https && h.forceHttps)) add(`${base}-web-static`, ["web"], {}, [...mws, `${p}-static`], staticRule);
      if (h.https) add(`${base}-secure-static`, ["websecure"], { tls }, [...mws, `${p}-static`], staticRule);
    }
  });

  const http: Obj = {};
  if (Object.keys(routers).length) http.routers = routers;
  if (Object.keys(middlewares).length) http.middlewares = middlewares;
  if (Object.keys(services).length) http.services = services;
  if (Object.keys(transports).length) http.serversTransports = transports;
  const doc: Obj = Object.keys(http).length ? { http } : {};
  if (certificates.length) doc.tls = { certificates };
  return `${GENERATED} ${site.title}.\n${Object.keys(doc).length ? YAML.stringify(doc) : ""}`;
}

export type ExpectedRouter = { name: string; service: string; middlewares: string[] };

/** Routers a site file defines, with their service and middlewares (to confirm Traefik loaded this exact version). */
export function traefikRouters(content: string): ExpectedRouter[] {
  try {
    const doc = YAML.parse(content) as { http?: { routers?: Record<string, { service?: string; middlewares?: string[] }> } };
    return Object.entries(doc?.http?.routers ?? {}).map(([name, r]) => ({ name, service: r.service ?? "", middlewares: r.middlewares ?? [] }));
  } catch {
    return [];
  }
}

export function traefikRouterNames(content: string) {
  return traefikRouters(content).map((r) => r.name);
}
