services:
  stash:
    image: stashapp/stash:latest
    restart: unless-stopped
    environment:
      STASH_STASH: /data/
      STASH_GENERATED: /generated/
      STASH_METADATA: /metadata/
      STASH_CACHE: /cache/
      STASH_PORT: "9999"
      TZ: Etc/UTC
    volumes:
      - stash-config:/root/.stash
      - stash-data:/data
      - stash-metadata:/metadata
      - stash-cache:/cache
      - stash-blobs:/blobs
      - stash-generated:/generated
volumes:
  stash-config:
  stash-data:
  stash-metadata:
  stash-cache:
  stash-blobs:
  stash-generated:
