services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}/
      SEARXNG_SECRET: ${SEARXNG_SECRET}
    volumes:
      - searxng-config:/etc/searxng
volumes:
  searxng-config:
