services:
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    command: ["gotenberg", "--api-enable-basic-auth"]
    environment:
      GOTENBERG_API_BASIC_AUTH_USERNAME: ${GOTENBERG_USER}
      GOTENBERG_API_BASIC_AUTH_PASSWORD: ${GOTENBERG_PASSWORD}
