services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:0
    restart: unless-stopped
    environment:
      HBOX_LOG_LEVEL: info
      HBOX_OPTIONS_ALLOW_REGISTRATION: "true"
      HBOX_WEB_MAX_UPLOAD_SIZE: "10"
    volumes:
      - homebox-data:/data
volumes:
  homebox-data:
