services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      LT_LOAD_ONLY: ${LT_LOAD_ONLY}
      LT_UPDATE_MODELS: "true"
    volumes:
      - libretranslate-models:/home/libretranslate/.local
volumes:
  libretranslate-models:
