services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      USER: ${TRANSMISSION_USER}
      PASS: ${TRANSMISSION_PASSWORD}
      PEERPORT: "51413"
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
      - transmission-watch:/watch
volumes:
  transmission-config:
  transmission-downloads:
  transmission-watch:
