services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    volumes:
      - lidarr-config:/config
      - lidarr-music:/music
      - lidarr-downloads:/downloads
volumes:
  lidarr-config:
  lidarr-music:
  lidarr-downloads:
