services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    volumes:
      - grocy-config:/config
volumes:
  grocy-config:
