services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:26
    restart: unless-stopped
    environment:
      CB_SERVER_NAME: CloudBeaver
      CB_SERVER_URL: ${CB_SERVER_URL}
      CB_ADMIN_NAME: ${CB_ADMIN_NAME}
      CB_ADMIN_PASSWORD: ${CB_ADMIN_PASSWORD}
    volumes:
      - cloudbeaver-workspace:/opt/cloudbeaver/workspace
volumes:
  cloudbeaver-workspace:
