services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    volumes:
      - filebrowser-files:/srv
      - filebrowser-database:/database
      - filebrowser-config:/config
volumes:
  filebrowser-files:
  filebrowser-database:
  filebrowser-config:
